#! /bin/bash
#
# Script Name: OSF
# Script URL: https://madpony.co/open-source/
# Version: 1.0.0
# Author: James Pond
# Author URL: https://madpony.co/
# License: GNU General Public License v2 or later
# License URI: http://www.gnu.org/licenses/gpl-2.0.html
#

# Must be run using root or sudo.
if [[ $EUID -ne 0 ]]; then
  echo 'You must run this script as root or using sudo.'
  exit 1
fi

# If no arguments are used, display usage to the user.
if [  $# -le 0 ]; then
  echo 'USAGE'
  echo 'optimize-static-files <DOMAIN>'
  exit 1
fi

# Variables that are going to help us.
DOMAIN="$1"

# Create .gz and .br files.
find /srv/"$DOMAIN"/www/ -type f -a \( -name '*.html' -o -name '*.css' -o -name '*.js' -o -name '*.json' -o -name '*.xml' -o -name '*.svg' -o -name '*.txt' \) -exec gzip -fkv9 {} \;
find /srv/"$DOMAIN"/www/ -type f -a \( -name '*.html' -o -name '*.css' -o -name '*.js' -o -name '*.json' -o -name '*.xml' -o -name '*.svg' -o -name '*.txt' \) -exec brotli -fvZ {} \;

# Lossless image optimization with jpegoptim
# and optipng.
find /srv/"$DOMAIN"/www/wp-content/ -type f -name "*.jp*" -exec jpegoptim -m76 --strip-all {} \;
find /srv/"$DOMAIN"/www/wp-content/ -type f -name "*.png" -exec optipng -o7 -preserve {} \;
